name: Travel Website Automation CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Selenium WebDriver (ChromeDriver)
        run: |
          Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip -OutFile chromedriver.zip
          Expand-Archive -Path chromedriver.zip -DestinationPath .
          Move-Item -Path .\chromedriver.exe -Destination C:\Windows\System32

      - name: Run Tests with Pytest
        run: |
          pytest --maxfail=5 --disable-warnings -v

  generate_reports:
    runs-on: windows-latest
    needs: setup

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies for Reports
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run Tests and Generate Allure Reports
        run: |
          pytest --alluredir=allure-results
          allure serve allure-results
